language: node_js
node_js:
  - "10"

sudo: false

install:
  - npm install

env:
  - SCRIPT=test
  - SCRIPT=lint-check
  - SCRIPT=pretty-check

script:
  - npm run $SCRIPT

matrix:
  allow_failures:
    - env: SCRIPT=lint-check
    - env: SCRIPT=pretty-check

after_success:
#  - npm run shim:coverage && npm run shim:coveralls
