language: node_js
node_js:
  - "10"

sudo: false

install:
  - npm install

script:
  - npm run test

matrix:
  include:
    - env: LINT
      script:
      - npm run lint-check
      - npm run pretty-check
  allow_failures:
    - env: LINT

after_success:
#  - npm run shim:coverage && npm run shim:coveralls

branches:
  only:
    - master
