version: 2.0

references:

  node11: &node11image
    docker:
      - image: circleci/node:11

  node10: &node10image
    docker:
      - image: circleci/node:10

  node9: &node9image
    docker:
      - image: circleci/node:9

  node8: &node8image
    docker:
      - image: circleci/node:8

  node7: &node7image
    docker:
      - image: circleci/node:7

  node11browser: &node11browsersimage
    docker:
      - image: circleci/node:11-browsers

  node10browser: &node10browsersimage
    docker:
      - image: circleci/node:10-browsers

  node9browser: &node9browsersimage
    docker:
      - image: circleci/node:9-browsers

  node8browser: &node8browsersimage
    docker:
      - image: circleci/node:8-browsers

  node7browser: &node7browsersimage
    docker:
      - image: circleci/node:7-browsers

  install_npm_default: &install_npm
    run: 
      name: Update npm
      command: 'sudo npm install -g npm@latest'
  restore_cache_default: &restore_cache # special step to restore the dependency cache
    restore_cache:
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        key: dependency-cache-{{ checksum "package.json" }}
  install_npm_packages_default: &install_npm_packages
    run:
        name: Install npm packages
        command: npm install
  save_cache_default: &save_cache # special step to save the dependency cache
    save_cache: 
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
  update_realm_submodule_default: &update_realm_submodule
    run: 
        name: Git Submodule Update
        command: git submodule update --init --recursive

    
jobs:

  # Lint and Test

  lint_and_test_node_11: &lint_and_test
    <<: *node11image
    steps: 
      - checkout
      - *update_realm_submodule
      - *install_npm
      - *restore_cache
      - *install_npm_packages
      - *save_cache
      - run: &lint
          name: Lint
          command: npm run lint-check
      - run: &test
          name: Test
          command: npm test

  lint_and_test_node_10:
    <<: *lint_and_test
    <<: *node10image
      
  lint_and_test_node_9:
    <<: *lint_and_test
    <<: *node9image

  lint_and_test_node_8:
    <<: *lint_and_test
    <<: *node8image

  lint_and_test_node_7:
    <<: *lint_and_test
    <<: *node7image

  # Pre-Release Test Integration

  pre_release_test_integration_node_11: &pre_release_test_integration
    <<: *node11browsersimage
    steps: 
      - checkout
      - *update_realm_submodule
      - *install_npm
      - *restore_cache
      - *install_npm_packages
      - *save_cache
      - run:
          name: Build browser tests and bundle
          command: ./integration-test/scripts/build-pre-release-test.sh
      - run:
          name: Test bundles
          command: |
            cd integration-test
            npm run test:pre-release

  pre_release_test_integration_node_10:
    <<: *pre_release_test_integration
    <<: *node10browsersimage
  
  pre_release_test_integration_node_9:
    <<: *pre_release_test_integration
    <<: *node9browsersimage
  
  pre_release_test_integration_node_8:
    <<: *pre_release_test_integration
    <<: *node8browsersimage
  
  pre_release_test_integration_node_7:
    <<: *pre_release_test_integration
    <<: *node7browsersimage

  # Post-Release Test Integration

  post_release_test_integration_node_11: &post_release_test_integration
    <<: *node11browsersimage
    steps: 
      - checkout
      - *update_realm_submodule
      - *install_npm
      - *restore_cache
      - *install_npm_packages
      - *save_cache
      - run:
          name: Build browser tests
          command: ./integration-test/scripts/build-post-release-test.sh
      - run:
          name: Test unpkg
          command: |
            cd integration-test
            npm run test:post-release

  post_release_test_integration_node_10:
    <<: *post_release_test_integration
    <<: *node10browsersimage

  post_release_test_integration_node_9:
    <<: *post_release_test_integration
    <<: *node9browsersimage

  post_release_test_integration_node_8:
    <<: *post_release_test_integration
    <<: *node8browsersimage

  post_release_test_integration_node_7:
    <<: *post_release_test_integration
    <<: *node7browsersimage 

  npm_audit_node_11: &npm_audit
    docker:
      - image: circleci/golang:1.12.0-node
    steps: 
      - checkout
      - run: 
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install hub
          command: |
              set -xe
              go get -u -d github.com/github/hub
              cd /go/src/github.com/github/hub
              go install github.com/github/hub
      - run:
          name: Submit PR if npm audit fix makes changes
          command: ./scripts/npm-audit-fix.sh


workflows:
  version: 2
  test_all:
    jobs:
      - lint_and_test_node_11
      - lint_and_test_node_10
      - pre_release_test_integration_node_11
      - pre_release_test_integration_node_10
  nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
        - npm_audit_node_11
        - post_release_test_integration_node_11
        - post_release_test_integration_node_10
